import React, { useState } from 'react';
import ReactMarkdown from 'react-markdown';
import remarkGfm from 'remark-gfm';
import { Prism as SyntaxHighlighter } from 'react-syntax-highlighter';
import { atomDark } from 'react-syntax-highlighter/dist/esm/styles/prism';
import { Check, Copy, Download, Share2 } from 'lucide-react';

function MarkdownImage({ src, alt }) {
  const [copied, setCopied] = useState(false);
  const [downloaded, setDownloaded] = useState(false);

  const handleCopyImage = async () => {
    try {
      await navigator.clipboard.writeText(src);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch (e) {
      console.error(e);
    }
  };

  const handleDownloadImage = async () => {
    try {
      const response = await fetch(src);
      const blob = await response.blob();
      const url = window.URL.createObjectURL(blob);
      const link = document.createElement('a');
      link.href = url;
      link.download = `powerful-ai-${Date.now()}.png`;
      document.body.appendChild(link);
      link.click();
      document.body.removeChild(link);
      window.URL.revokeObjectURL(url);
      setDownloaded(true);
      setTimeout(() => setDownloaded(false), 2000);
    } catch (e) {
      window.open(src, '_blank');
    }
  };

  const handleShareImage = async () => {
    try {
      if (navigator.share) {
        await navigator.share({
          title: alt || 'Generated by Powerful AI',
          url: src,
        });
      } else {
        await navigator.clipboard.writeText(src);
        alert('Image link copied to clipboard!');
      }
    } catch (e) {
      console.error(e);
    }
  };

  return (
    <div className="relative group my-2 max-w-full bg-transparent border-0 outline-none p-0 m-0">
      <img 
        src={src} 
        alt={alt || "AI Generated Image"} 
        className="rounded-3xl max-w-full object-cover max-h-[650px] transition-transform duration-300 shadow-2xl border-0 bg-transparent"
        loading="lazy"
      />
      <div className="flex items-center gap-1.5 mt-2.5 bg-black/60 dark:bg-zinc-800/80 backdrop-blur-md px-3.5 py-1.5 rounded-full w-fit shadow-md">
        <button
          onClick={handleCopyImage}
          className="flex items-center gap-1.5 text-xs font-semibold text-white/90 hover:text-white hover:bg-white/10 px-2.5 py-1 rounded-full transition-colors"
          title="Copy Image URL"
        >
          {copied ? <Check size={14} className="text-green-400" /> : <Copy size={14} />}
          <span>{copied ? 'Copied' : 'Copy'}</span>
        </button>
        <button
          onClick={handleDownloadImage}
          className="flex items-center gap-1.5 text-xs font-semibold text-white/90 hover:text-white hover:bg-white/10 px-2.5 py-1 rounded-full transition-colors"
          title="Download Image"
        >
          {downloaded ? <Check size={14} className="text-green-400" /> : <Download size={14} />}
          <span>{downloaded ? 'Saved' : 'Download'}</span>
        </button>
        <button
          onClick={handleShareImage}
          className="flex items-center gap-1.5 text-xs font-semibold text-white/90 hover:text-white hover:bg-white/10 px-2.5 py-1 rounded-full transition-colors"
          title="Share Image"
        >
          <Share2 size={14} />
          <span>Share</span>
        </button>
      </div>
    </div>
  );
}

export default function MarkdownRenderer({ content }) {
  let processedContent = content || '';
  const mdImageRegex = /!\[([^\]]*)\]\(([^)]+)\)/g;
  processedContent = processedContent.replace(mdImageRegex, (match, alt, url) => {
    if (url.includes(' ')) {
      return `![${alt}](${encodeURI(url.trim())})`;
    }
    return match;
  });

  return (
    <div className="markdown-body text-[15px] md:text-[15.5px] leading-relaxed space-y-2 text-textMain font-normal">
      <ReactMarkdown
        remarkPlugins={[remarkGfm]}
        components={{
          p({ node, children }) {
            return <p className="mb-4 last:mb-0 leading-relaxed text-textMain">{children}</p>;
          },
          a({ node, children, href }) {
            return (
              <a href={href} target="_blank" rel="noopener noreferrer" className="text-primary hover:underline font-medium">
                {children}
              </a>
            );
          },
          ul({ node, children }) {
            return <ul className="list-disc pl-6 mb-4 space-y-1.5 marker:text-primary/70">{children}</ul>;
          },
          ol({ node, children }) {
            return <ol className="list-decimal pl-6 mb-4 space-y-1.5 marker:text-primary/70">{children}</ol>;
          },
          h1({ node, children }) {
            return <h1 className="text-2xl font-bold mt-6 mb-3 text-textMain">{children}</h1>;
          },
          h2({ node, children }) {
            return <h2 className="text-xl font-bold mt-5 mb-2.5 text-textMain/95">{children}</h2>;
          },
          h3({ node, children }) {
            return <h3 className="text-lg font-bold mt-4 mb-2 text-textMain/90">{children}</h3>;
          },
          strong({ node, children }) {
            return <strong className="font-semibold text-textMain">{children}</strong>;
          },
          img({ node, src, alt }) {
            return <MarkdownImage src={src} alt={alt} />;
          },
          code({ node, inline, className, children, ...props }) {
            const match = /language-(\w+)/.exec(className || '');
            const isMultiLine = String(children).includes('\n') || String(children).length > 80;
            const [copied, setCopied] = useState(false);
            const [downloaded, setDownloaded] = useState(false);

            const labelText = match ? match[1].charAt(0).toUpperCase() + match[1].slice(1) : 'Plaintext';

            const handleCopy = () => {
              navigator.clipboard.writeText(String(children).replace(/\n$/, ''));
              setCopied(true);
              setTimeout(() => setCopied(false), 2000);
            };

            const handleDownload = () => {
              const extMap = {
                python: 'py', javascript: 'js', typescript: 'ts', jsx: 'jsx', tsx: 'tsx',
                html: 'html', css: 'css', json: 'json', markdown: 'md', prompt: 'txt',
                email: 'txt', lyrics: 'txt', shayari: 'txt', plaintext: 'txt'
              };
              const ext = (match && extMap[match[1].toLowerCase()]) || 'txt';
              const blob = new Blob([String(children)], { type: 'text/plain' });
              const url = window.URL.createObjectURL(blob);
              const link = document.createElement('a');
              link.href = url;
              link.download = `powerful-ai-${labelText.toLowerCase()}.${ext}`;
              document.body.appendChild(link);
              link.click();
              document.body.removeChild(link);
              window.URL.revokeObjectURL(url);
              setDownloaded(true);
              setTimeout(() => setDownloaded(false), 2000);
            };

            if (!inline && (match || isMultiLine)) {
              return (
                <div className="relative group rounded-3xl overflow-hidden my-4 bg-[#18181b] dark:bg-zinc-900 border border-white/10 shadow-md text-gray-200">
                  <div className="flex items-center justify-between px-5 pt-3.5 pb-2 bg-white/[0.03] border-b border-white/10 text-xs text-gray-400">
                    <span className="font-medium tracking-wide text-gray-300">{labelText}</span>
                    <div className="flex items-center gap-2">
                      <button
                        onClick={handleDownload}
                        className="flex items-center gap-1.5 hover:text-white transition-colors px-2.5 py-1 rounded-lg hover:bg-white/10"
                        title="Download file"
                      >
                        {downloaded ? (
                          <>
                            <Check size={14} className="text-green-400" />
                            <span className="text-green-400 font-medium">Saved</span>
                          </>
                        ) : (
                          <>
                            <Download size={14} />
                            <span>Download</span>
                          </>
                        )}
                      </button>
                      <button
                        onClick={handleCopy}
                        className="flex items-center gap-1.5 hover:text-white transition-colors px-2.5 py-1 rounded-lg hover:bg-white/10"
                        title="Copy to clipboard"
                      >
                        {copied ? (
                          <>
                            <Check size={14} className="text-green-400" />
                            <span className="text-green-400 font-medium">Copied</span>
                          </>
                        ) : (
                          <>
                            <Copy size={14} />
                            <span>Copy</span>
                          </>
                        )}
                      </button>
                    </div>
                  </div>
                  <SyntaxHighlighter
                    {...props}
                    style={atomDark}
                    language={match ? match[1] : 'text'}
                    PreTag="div"
                    customStyle={{
                      margin: 0,
                      padding: '1.25rem 1.5rem',
                      background: 'transparent',
                      fontSize: '0.9rem',
                      lineHeight: '1.6',
                      fontFamily: `'JetBrains Mono', 'Fira Code', 'Courier New', monospace`
                    }}
                  >
                    {String(children).replace(/\n$/, '')}
                  </SyntaxHighlighter>
                </div>
              );
            }
            return (
              <code {...props} className="bg-primary/15 text-primary-light px-2 py-0.5 rounded-lg font-mono text-[13.5px]">
                {children}
              </code>
            );
          }
        }}
      >
        {processedContent}
      </ReactMarkdown>
    </div>
  );
}
